import { describe, it, expect } from 'vitest'

// The REAL client parser and the REAL platform->extension map. Imported, not
// mirrored: this gate's only claim is "green means the client can verify this
// release", and the differential suite below is what keeps that claim true.
import {
  digestForAsset as clientDigestForAsset,
  installerExtForPlatform,
  MAX_MANIFEST_BYTES as CLIENT_MAX_MANIFEST_BYTES,
} from '../../../src/main/github-update'

// verify-release-manifest.js is plain Node.js (CommonJS) and guards main()
// behind `require.main === module`, so require()-ing it here imports the
// helpers without shelling out to gh.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const verify = require('../../../scripts/verify-release-manifest.js') as {
  splitChecksumLine: (line: string) => [string, string] | null
  digestForAsset: (manifest: string, assetName: string) => string | null
  isInstaller: (name: string) => boolean
  normalizeApiDigest: (digest: unknown) => string | null
  auditManifest: (input: {
    attached: Array<string | { name: string; digest?: string | null }>
    manifestText: string | null
    manifestBytes?: number | null
  }) => {
    ok: boolean
    reason: string | null
    installers: string[]
    problems: Array<{ name: string; why: string }>
    warnings: string[]
  }
  withRetry: <T>(fn: () => T, opts?: { attempts?: number; sleep?: (ms: number) => void; log?: (m: string) => void }) => T
  main: (deps: {
    argv?: string[]
    env?: Record<string, string>
    runGh?: (args: string[]) => string
    sleep?: (ms: number) => void
    log?: (m: string) => void
    errLog?: (m: string) => void
    tmpdir?: () => string
  }) => number
  INSTALLER_EXTENSIONS: string[]
  MAX_MANIFEST_BYTES: number
  EXIT_OK: number
  EXIT_BROKEN_RELEASE: number
  EXIT_CANNOT_VERIFY: number
}

const { isInstaller, normalizeApiDigest, auditManifest, withRetry, main } = verify
const { EXIT_OK, EXIT_BROKEN_RELEASE, EXIT_CANNOT_VERIFY, MAX_MANIFEST_BYTES } = verify

const HASH_A = 'a'.repeat(64)
const HASH_B = 'b'.repeat(64)

const EXE = 'ClaudeCommandCenter-2.1.0-beta.5.exe'
const DMG = 'ClaudeCommandCenter-2.1.0-beta.5-mac.dmg'
const APPIMAGE = 'ClaudeCommandCenter-2.1.0-beta.5-linux-x86_64.AppImage'

/** A manifest line in the shape GNU sha256sum emits on ubuntu (text mode). */
function line(hash: string, name: string): string {
  return `${hash}  ${name}`
}

/** Assets of a healthy three-platform release, with matching API digests. */
function healthyRelease(): { attached: Array<{ name: string; digest: string | null }>; manifestText: string } {
  const entries: Array<[string, string]> = [
    [HASH_A, EXE],
    [HASH_B, DMG],
    ['c'.repeat(64), APPIMAGE],
  ]
  return {
    attached: [
      { name: 'CHECKSUMS.txt', digest: `sha256:${'f'.repeat(64)}` },
      ...entries.map(([h, n]) => ({ name: n, digest: `sha256:${h}` })),
      { name: `${EXE}.blockmap`, digest: `sha256:${'d'.repeat(64)}` },
      { name: 'latest.yml', digest: `sha256:${'e'.repeat(64)}` },
    ],
    manifestText: entries.map(([h, n]) => line(h, n)).join('\n') + '\n',
  }
}

// ============================================================
// The differential suite. This is the guard that matters.
// ============================================================

describe('parser parity with the real client (src/main/github-update.ts)', () => {
  // Every input the adversarial pass on #173 used to break the first draft,
  // plus the shapes github-update.ts documents. If the port ever drifts from
  // the client, one of these disagrees and this suite goes red.
  const CORPUS: Array<[string, string]> = [
    ['plain text mode', line(HASH_A, EXE)],
    ['binary mode (space asterisk)', `${HASH_A} *${EXE}`],
    ['tab separator', `${HASH_A}\t${EXE}`],
    ['path-prefixed name', line(HASH_A, `artifacts/${EXE}`)],
    ['backslash path-prefixed name', line(HASH_A, `artifacts\\${EXE}`)],
    ['./ prefixed name', line(HASH_A, `./${EXE}`)],
    ['leading whitespace on the line', `   ${line(HASH_A, EXE)}`],
    ['trailing whitespace on the line', `${line(HASH_A, EXE)}   `],
    ['comment line then the real line', `# generated by hand\n${line(HASH_A, EXE)}`],
    ['duplicate identical lines', `${line(HASH_A, EXE)}\n${line(HASH_A, EXE)}`],
    ['duplicate same digest, different hex case', `${line(HASH_A, EXE)}\n${line(HASH_A.toUpperCase(), EXE)}`],
    ['star immediately after the digest', `${HASH_A}* ${EXE}`],
    ['65 hex then a space', `${'a'.repeat(65)} ${EXE}`],
    ['star separated from the name by a space', `${HASH_A}  * ${EXE}`],
    ['duplicate CONFLICTING digests', `${line(HASH_A, EXE)}\n${line(HASH_B, EXE)}`],
    ['duplicate conflicting via path prefix', `${line(HASH_A, EXE)}\n${line(HASH_B, `artifacts/${EXE}`)}`],
    ['non-breaking space as separator', `${HASH_A} ${EXE}`],
    ['form feed as separator', `${HASH_A}\f${EXE}`],
    ['double separator run then a stray whitespace', `${HASH_A}  ${EXE}`],
    ['U+2028 inside the name', `${HASH_A}  x ${EXE}`],
    ['UTF-8 BOM before the digest', `﻿${line(HASH_A, EXE)}`],
    ['GNU backslash-escaped line', `\\${line(HASH_A, `we\\\\ird-${EXE}`)}`],
    ['hash one char short', line('a'.repeat(63), EXE)],
    ['hash one char long', line('a'.repeat(65), EXE)],
    ['non-hex hash', line('z'.repeat(64), EXE)],
    ['name only, no hash', EXE],
    ['empty manifest', ''],
    ['whitespace-only manifest', '   \n\t\n'],
    ['CRLF line endings', `${line(HASH_A, EXE)}\r\n${line(HASH_B, DMG)}\r\n`],
    ['lone CR separators', `${line(HASH_A, EXE)}\r${line(HASH_B, DMG)}`],
    ['name that itself looks like a checksum line', line(HASH_A, line(HASH_B, EXE))],
    ['uppercase hex digest', line(HASH_A.toUpperCase(), EXE)],
    ['name differing only in case', line(HASH_A, EXE.toUpperCase())],
    ['trailing dot on the name', line(HASH_A, `${EXE}.`)],
    ['healthy three-line manifest', [line(HASH_A, EXE), line(HASH_B, DMG), line('c'.repeat(64), APPIMAGE)].join('\n')],
  ]

  const QUERIES = [EXE, DMG, APPIMAGE, EXE.toUpperCase(), `artifacts/${EXE}`, '']

  for (const [label, manifestText] of CORPUS) {
    it(`agrees with the client: ${label}`, () => {
      for (const query of QUERIES) {
        expect(
          verify.digestForAsset(manifestText, query),
          `disagreed on query "${query}" for manifest case "${label}"`,
        ).toBe(clientDigestForAsset(manifestText, query))
      }
    })
  }

  it('agrees with the client on the real published v2.1.0-beta.5 manifest', () => {
    // Verbatim bytes of the CHECKSUMS.txt attached to v2.1.0-beta.5.
    const real = [
      'f65c31f427d587595e340477d5375ebfb8e1fdb207bebf943d8d77d63a1f2752  ClaudeCommandCenter-2.1.0-beta.5-linux-x86_64.AppImage',
      'fc5a00c2b2518fe898a6f2cc4c74fe446a8648d7ef2cdbd901574020f27db9d0  ClaudeCommandCenter-2.1.0-beta.5-mac.dmg',
      '913a513f0c36a5163fc2d1a1524f3ef3f8063754fb63c61add7242c6c1ca20bb  ClaudeCommandCenter-2.1.0-beta.5-mac.dmg.blockmap',
      'ae5db5b58972ae410ba05fed86d8c6c4382a024c31373fa71bf8fcb5b7938cc7  ClaudeCommandCenter-2.1.0-beta.5.exe',
      'b914537c5214dd5471e7a2ea0fc569d599afa1f8dfe15dbe1ae3f08bf9ae5d96  ClaudeCommandCenter-2.1.0-beta.5.exe.blockmap',
      '97697fbba0fbbe3d75c66f6de8c5697e1192f9a54e550410149d0db4fe0d19a8  latest-linux.yml',
      '896a46bce3d1abdc9ddd0d8d8e726030451fa2cc5b295688b43596faa76510b1  latest-mac.yml',
      '6b8747fdc7d67a7f8c1691a8e84f07664886afdeacc1281b64401388c2c403a0  latest.yml',
    ].join('\n') + '\n'
    for (const name of [EXE, DMG, APPIMAGE, 'latest.yml', 'not-attached.exe']) {
      expect(verify.digestForAsset(real, name)).toBe(clientDigestForAsset(real, name))
    }
    expect(verify.digestForAsset(real, EXE)).toBe('ae5db5b58972ae410ba05fed86d8c6c4382a024c31373fa71bf8fcb5b7938cc7')
  })

  it('parses a pathological manifest in linear time, like the client', () => {
    // The quadratic regex this file originally used took 15.5 s on 128k of
    // spaces followed by a U+2028 tail. github-update.ts carries the same
    // guard (tests/unit/main/github-update-redos.test.ts) because the repo has
    // paid for this shape twice.
    const hostile = `${HASH_A}${' '.repeat(200_000)}x y`
    const start = Date.now()
    expect(verify.digestForAsset(hostile, EXE)).toBeNull()
    expect(Date.now() - start).toBeLessThan(1000)
  })
})

describe('INSTALLER_EXTENSIONS covers what the client will fetch', () => {
  it('gates every extension installerExtForPlatform can return', () => {
    // Duplicated knowledge, bound by a test. Adding an electron-builder target
    // (say a .msi) and updating installerExtForPlatform would otherwise leave
    // the new installer kind silently exempt from this gate forever.
    for (const platform of ['win32', 'darwin', 'linux'] as NodeJS.Platform[]) {
      const ext = installerExtForPlatform(platform)
      expect(isInstaller(`ClaudeCommandCenter-1.0.0${ext}`), `${platform} -> ${ext} is not gated`).toBe(true)
    }
  })

  it('gates a strict superset of the client, never a subset', () => {
    // The client is case-SENSITIVE and requires a ClaudeCommandCenter- prefix.
    // Over-covering can only fail a release that would have worked;
    // under-covering ships the dead end. Pin the direction.
    expect(isInstaller('anything.appimage')).toBe(true)
    expect(isInstaller('anything.EXE')).toBe(true)
    expect(isInstaller('third-party-tool.exe')).toBe(true)
  })
})

describe('isInstaller', () => {
  it('accepts the three installer kinds', () => {
    expect(isInstaller(EXE)).toBe(true)
    expect(isInstaller(DMG)).toBe(true)
    expect(isInstaller(APPIMAGE)).toBe(true)
  })

  it('ignores everything else attached to a release', () => {
    expect(isInstaller('CHECKSUMS.txt')).toBe(false)
    expect(isInstaller('latest.yml')).toBe(false)
    expect(isInstaller(`${EXE}.blockmap`)).toBe(false)
    expect(isInstaller(`${DMG}.blockmap`)).toBe(false)
  })

  it('does not treat the extension appearing mid-name as a match', () => {
    // The fixtures must CONTAIN the dotted extension, or an `endsWith` ->
    // `includes` regression sails past the very test named for it.
    expect(isInstaller('notes-about-.exe-files.txt')).toBe(false)
    expect(isInstaller('release-.dmg-notes.txt')).toBe(false)
    expect(isInstaller('.appimage-packaging.md')).toBe(false)
  })
})

describe('constants the workflow and the client depend on', () => {
  it('pins the exit-code contract release.yml keys on', () => {
    // release.yml captures the exit code and gates the withdraw step on `== 1`.
    // Asserting against the module's own constants would be x === x: setting
    // every EXIT_* to 0 must not leave this suite green while the gate
    // publishes a release the client will refuse.
    expect(EXIT_OK).toBe(0)
    expect(EXIT_BROKEN_RELEASE).toBe(1)
    expect(EXIT_CANNOT_VERIFY).toBe(2)
  })

  it('uses the same manifest cap as the client', () => {
    // Imported from src/main/github-update, not mirrored. A gate whose cap is
    // larger than the client's accepts a manifest the client refuses before
    // parsing — green CI, uninstallable release.
    expect(MAX_MANIFEST_BYTES).toBe(CLIENT_MAX_MANIFEST_BYTES)
    expect(MAX_MANIFEST_BYTES).toBe(1024 * 1024)
  })
})

describe('normalizeApiDigest', () => {
  it('accepts the sha256: prefixed form gh returns', () => {
    expect(normalizeApiDigest(`sha256:${HASH_A}`)).toBe(HASH_A)
  })
  it('accepts a bare hex digest and lowercases it', () => {
    expect(normalizeApiDigest(HASH_A.toUpperCase())).toBe(HASH_A)
  })
  it('returns null for anything that is not a sha256 digest', () => {
    // Null must mean "cannot compare", never "matches" — a truncated or
    // md5-shaped value has to degrade to a warning, not a silent pass.
    expect(normalizeApiDigest(null)).toBeNull()
    expect(normalizeApiDigest(undefined)).toBeNull()
    expect(normalizeApiDigest('')).toBeNull()
    expect(normalizeApiDigest('sha256:')).toBeNull()
    expect(normalizeApiDigest(`sha512:${HASH_A}`)).toBeNull()
    expect(normalizeApiDigest('a'.repeat(63))).toBeNull()
  })
})

describe('auditManifest', () => {
  it('passes a healthy three-platform release', () => {
    const { attached, manifestText } = healthyRelease()
    const result = auditManifest({ attached, manifestText })
    expect(result.ok).toBe(true)
    expect(result.problems).toEqual([])
    expect(result.warnings).toEqual([])
    expect(result.installers.sort()).toEqual([APPIMAGE, DMG, EXE].sort())
  })

  it('fails the stale-asset case: an attached AppImage the new manifest never listed', () => {
    // The case #173 exists for.
    const { attached } = healthyRelease()
    const result = auditManifest({
      attached,
      manifestText: [line(HASH_A, EXE), line(HASH_B, DMG)].join('\n'),
    })
    expect(result.ok).toBe(false)
    expect(result.problems.map((p) => p.name)).toEqual([APPIMAGE])
  })

  it('fails a manifest with two conflicting lines for one installer, as the client does', () => {
    // The false PASS the first draft shipped. digestForAsset returns null here
    // and the client throws; the gate must agree.
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', EXE, DMG, APPIMAGE],
      manifestText: [line(HASH_A, EXE), line(HASH_B, EXE), line(HASH_B, DMG), line(HASH_A, APPIMAGE)].join('\n'),
    })
    expect(result.ok).toBe(false)
    expect(result.problems.map((p) => p.name)).toEqual([EXE])
  })

  it('fails when the manifest names the asset but describes different bytes', () => {
    // The non-atomic --clobber case: CHECKSUMS.txt landed, the installer upload
    // flaked, so the OLD binary is attached under the NEW manifest's digest.
    // Name coverage alone would call this healthy.
    const result = auditManifest({
      attached: [
        { name: 'CHECKSUMS.txt', digest: null },
        { name: EXE, digest: `sha256:${HASH_B}` },
        { name: DMG, digest: `sha256:${HASH_B}` },
        { name: APPIMAGE, digest: `sha256:${'c'.repeat(64)}` },
      ],
      manifestText: [line(HASH_A, EXE), line(HASH_B, DMG), line('c'.repeat(64), APPIMAGE)].join('\n'),
    })
    expect(result.ok).toBe(false)
    expect(result.problems.map((p) => p.name)).toEqual([EXE])
    expect(result.problems[0].why).toMatch(/attached asset is/)
  })

  it('warns, and records no byte check, when the API gives no digest', () => {
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', EXE, DMG, APPIMAGE],
      manifestText: [line(HASH_A, EXE), line(HASH_B, DMG), line('c'.repeat(64), APPIMAGE)].join('\n'),
    })
    expect(result.ok).toBe(true)
    expect(result.warnings.filter((w) => w.includes('no digest from the API'))).toHaveLength(3)
    // main() turns an all-line-only audit into CANNOT_VERIFY. That only works
    // if byteChecked actually stays empty here.
    expect(result.byteChecked).toEqual([])
  })

  it('records which installers had their bytes checked', () => {
    const { attached, manifestText } = healthyRelease()
    const result = auditManifest({ attached, manifestText })
    expect(result.byteChecked.sort()).toEqual([APPIMAGE, DMG, EXE].sort())
  })

  it('does not count a digest MISMATCH as byte-checked', () => {
    const result = auditManifest({
      attached: [
        { name: 'CHECKSUMS.txt', digest: null },
        { name: EXE, digest: `sha256:${HASH_B}` },
      ],
      manifestText: line(HASH_A, EXE),
    })
    expect(result.ok).toBe(false)
    expect(result.byteChecked).toEqual([])
  })

  it('does not let an under-reported byte count walk an oversized manifest past the cap', () => {
    const oversized = line(HASH_A, EXE) + '\n' + '#'.repeat(MAX_MANIFEST_BYTES + 10)
    const result = auditManifest({ attached: ['CHECKSUMS.txt', EXE], manifestText: oversized, manifestBytes: 42 })
    expect(result.ok).toBe(false)
    expect(result.reason).toMatch(/over the/)
  })

  it('does not let another asset line cover an installer whose own line is absent', () => {
    // A raw `manifestText.includes(name)` implementation passes this release,
    // because the blockmap line contains the installer name as a substring.
    // That is the #111 substring bug, and this is the fixture that catches it.
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', EXE, DMG, APPIMAGE],
      manifestText: [line(HASH_A, `${EXE}.blockmap`), line(HASH_B, DMG), line('c'.repeat(64), APPIMAGE)].join('\n'),
    })
    expect(result.ok).toBe(false)
    expect(result.problems.map((p) => p.name)).toEqual([EXE])
  })

  it('does not accept a prefix or suffix match for an installer name', () => {
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', 'evil-CCC-2.1.0.exe'],
      manifestText: line(HASH_A, 'CCC-2.1.0.exe'),
    })
    expect(result.ok).toBe(false)
    expect(result.problems.map((p) => p.name)).toEqual(['evil-CCC-2.1.0.exe'])
  })

  it('accepts a path-prefixed manifest name, as the client does', () => {
    // `sha256sum artifacts/*` instead of `cd artifacts && sha256sum *` is a
    // one-character mistake. The client strips the prefix, so this gate must
    // too, or every release hard-fails while every client is fine.
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', EXE, DMG, APPIMAGE],
      manifestText: [line(HASH_A, `artifacts/${EXE}`), line(HASH_B, `artifacts/${DMG}`), line('c'.repeat(64), `artifacts/${APPIMAGE}`)].join('\n'),
    })
    expect(result.ok).toBe(true)
  })

  it('fails when CHECKSUMS.txt is not attached at all', () => {
    const result = auditManifest({ attached: [EXE, DMG], manifestText: line(HASH_A, EXE) })
    expect(result.ok).toBe(false)
    expect(result.reason).toMatch(/not attached/)
  })

  it('does not let a .sig or a case variant stand in for the manifest', () => {
    // The client hard-codes the literal name in both fetch paths, so only the
    // exact spelling counts. Forward-looking for #172, which adds a .sig.
    const result = auditManifest({
      attached: ['CHECKSUMS.txt.sig', 'checksums.txt', EXE],
      manifestText: line(HASH_A, EXE),
    })
    expect(result.ok).toBe(false)
    expect(result.reason).toMatch(/not attached/)
  })

  it('fails when CHECKSUMS.txt is attached but unreadable', () => {
    const result = auditManifest({ attached: ['CHECKSUMS.txt', EXE], manifestText: null })
    expect(result.ok).toBe(false)
    expect(result.reason).toMatch(/could not be read/)
  })

  it('fails on an empty manifest instead of treating it as covering nothing quietly', () => {
    const result = auditManifest({ attached: ['CHECKSUMS.txt', EXE, DMG, APPIMAGE], manifestText: '' })
    expect(result.ok).toBe(false)
    expect(result.problems.map((p) => p.name).sort()).toEqual([APPIMAGE, DMG, EXE].sort())
  })

  it('fails a manifest larger than the client will read', () => {
    // The client refuses over MAX_MANIFEST_BYTES before parsing, so a manifest
    // this gate accepts and the client refuses is a release that passes CI and
    // cannot be installed.
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', EXE],
      manifestText: line(HASH_A, EXE),
      manifestBytes: MAX_MANIFEST_BYTES + 1,
    })
    expect(result.ok).toBe(false)
    expect(result.reason).toMatch(/over the/)
  })

  it('fails a release with no installer rather than passing vacuously', () => {
    const result = auditManifest({ attached: ['CHECKSUMS.txt', 'latest.yml'], manifestText: line(HASH_A, 'latest.yml') })
    expect(result.ok).toBe(false)
    expect(result.reason).toMatch(/no installer/)
  })

  it('warns but does not fail when a platform installer is missing', () => {
    // build-linux is deliberately continue-on-error, so a Linux-less release is
    // legitimate. Failing here would block a release the required platforms
    // built fine.
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', EXE, DMG],
      manifestText: [line(HASH_A, EXE), line(HASH_B, DMG)].join('\n'),
    })
    expect(result.ok).toBe(true)
    expect(result.warnings.some((w) => w.includes('Linux'))).toBe(true)
  })

  it('reports every broken installer, not just the first', () => {
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', EXE, DMG, APPIMAGE],
      manifestText: line(HASH_A, 'latest.yml'),
    })
    expect(result.ok).toBe(false)
    expect(result.problems.map((p) => p.name).sort()).toEqual([APPIMAGE, DMG, EXE].sort())
  })

  it('ignores non-installer assets missing from the manifest', () => {
    const result = auditManifest({
      attached: ['CHECKSUMS.txt', EXE, DMG, APPIMAGE, `${EXE}.blockmap`, 'latest.yml'],
      manifestText: [line(HASH_A, EXE), line(HASH_B, DMG), line('c'.repeat(64), APPIMAGE)].join('\n'),
    })
    expect(result.ok).toBe(true)
  })
})

describe('withRetry', () => {
  it('returns the first success without sleeping', () => {
    const slept: number[] = []
    expect(withRetry(() => 'ok', { sleep: (ms) => slept.push(ms), log: () => {} })).toBe('ok')
    expect(slept).toEqual([])
  })

  it('retries with exponential backoff and succeeds on a later attempt', () => {
    // The release is queried immediately after `gh release create`, and the API
    // is eventually consistent. Without this, a 404 turns into a red gate on a
    // healthy release — and a gate that cries wolf is one people ignore.
    const slept: number[] = []
    let calls = 0
    const value = withRetry(
      () => {
        calls += 1
        if (calls < 3) throw new Error('release not found')
        return 'ok'
      },
      { sleep: (ms) => slept.push(ms), log: () => {} },
    )
    expect(value).toBe('ok')
    expect(calls).toBe(3)
    expect(slept).toEqual([2000, 4000])
  })

  it('rethrows after the last attempt and does not sleep past it', () => {
    const slept: number[] = []
    expect(() =>
      withRetry(
        () => {
          throw new Error('still down')
        },
        { attempts: 2, sleep: (ms) => slept.push(ms), log: () => {} },
      ),
    ).toThrow('still down')
    expect(slept).toEqual([2000])
  })

  it('gives up after the DEFAULT attempt budget, bounding total backoff', () => {
    // No `attempts` override on purpose: nothing else observes the default, so
    // raising it to 30 would leave every other test green while a genuinely
    // missing release hangs the job on 2^30 ms of backoff.
    const slept: number[] = []
    let calls = 0
    expect(() =>
      withRetry(
        () => {
          calls += 1
          throw new Error('gone')
        },
        { sleep: (ms) => slept.push(ms), log: () => {} },
      ),
    ).toThrow('gone')
    expect(calls).toBe(3)
    expect(slept).toEqual([2000, 4000])
  })
})

describe('main', () => {
  const silent = { log: () => {}, errLog: () => {}, sleep: () => {} }

  /** A fake `gh` that records its argv and serves a scripted release. */
  function fakeGh(opts: {
    assets: Array<{ name: string; digest?: string | null }>
    isDraft?: boolean
    manifest?: string | null
    dirFor?: (dir: string) => void
  }) {
    const calls: string[][] = []
    const runGh = (args: string[]): string => {
      calls.push(args)
      if (args[1] === 'view') {
        return JSON.stringify({ assets: opts.assets, isDraft: opts.isDraft === true })
      }
      if (opts.manifest === null || opts.manifest === undefined) throw new Error('no CHECKSUMS.txt')
      const fsMod = require('node:fs') as typeof import('fs')
      const pathMod = require('node:path') as typeof import('path')
      const dir = args[args.indexOf('--dir') + 1]
      if (opts.dirFor) opts.dirFor(dir)
      fsMod.writeFileSync(pathMod.join(dir, 'CHECKSUMS.txt'), opts.manifest, 'utf-8')
      return ''
    }
    return { calls, runGh }
  }

  it('exits CANNOT_VERIFY when no tag is given, without calling gh', () => {
    // Assert the CALL COUNT, not just the exit code: without it the test passes
    // identically when the guard is removed and gh is asked about a blank tag
    // three times over.
    const calls: string[][] = []
    const code = main({
      ...silent,
      argv: [],
      env: {},
      runGh: (args) => {
        calls.push(args)
        throw new Error('gh must not be called')
      },
    })
    expect(code).toBe(EXIT_CANNOT_VERIFY)
    expect(calls).toEqual([])
  })

  it('exits CANNOT_VERIFY when the tag is whitespace only, without calling gh', () => {
    // The workflow interpolates a job output; an empty one must not fall
    // through to gating some other release — or to three live API calls.
    const calls: string[][] = []
    const code = main({
      ...silent,
      argv: ['   '],
      env: {},
      runGh: (args) => {
        calls.push(args)
        throw new Error('gh must not be called')
      },
    })
    expect(code).toBe(EXIT_CANNOT_VERIFY)
    expect(calls).toEqual([])
  })

  it('asks gh for each asset name AND digest, and downloads only CHECKSUMS.txt', () => {
    // The digest half of this gate lives entirely in that `-q` expression. Drop
    // `digest` from it and every installer silently degrades to a line-only
    // check — with no other assertion, nothing notices.
    const manifest = [line(HASH_A, EXE), line(HASH_B, DMG), line('c'.repeat(64), APPIMAGE)].join('\n') + '\n'
    const { calls, runGh } = fakeGh({
      assets: [
        { name: 'CHECKSUMS.txt', digest: null },
        { name: EXE, digest: `sha256:${HASH_A}` },
        { name: DMG, digest: `sha256:${HASH_B}` },
        { name: APPIMAGE, digest: `sha256:${'c'.repeat(64)}` },
      ],
      manifest,
    })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh })).toBe(EXIT_OK)
    expect(calls[0]).toEqual(['release', 'view', 'v1.0.0', '--json', 'assets,isDraft', '-q', '{assets: [.assets[] | {name, digest}], isDraft: .isDraft}'])
    expect(calls[1].slice(0, 5)).toEqual(['release', 'download', 'v1.0.0', '--pattern', 'CHECKSUMS.txt'])
  })

  it('exits CANNOT_VERIFY when no asset digest was available, rather than reporting a pass', () => {
    // Every manifest LINE resolves, but not one byte was compared — half the
    // gate did nothing. Exiting 0 here is how the digest check would quietly
    // stop existing on an older gh or on GHES.
    const manifest = [line(HASH_A, EXE), line(HASH_B, DMG), line('c'.repeat(64), APPIMAGE)].join('\n') + '\n'
    const { runGh } = fakeGh({
      assets: [{ name: 'CHECKSUMS.txt' }, { name: EXE }, { name: DMG }, { name: APPIMAGE }],
      manifest,
    })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh })).toBe(EXIT_CANNOT_VERIFY)
  })

  it('exits BROKEN_RELEASE when the API digest disagrees with the downloaded manifest', () => {
    const { runGh } = fakeGh({
      assets: [
        { name: 'CHECKSUMS.txt', digest: null },
        { name: EXE, digest: `sha256:${HASH_B}` },
      ],
      manifest: line(HASH_A, EXE) + '\n',
    })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh })).toBe(EXIT_BROKEN_RELEASE)
  })

  it('exits BROKEN_RELEASE with the size reason when the manifest is over the cap', () => {
    const errors: string[] = []
    const { runGh } = fakeGh({
      assets: [{ name: 'CHECKSUMS.txt', digest: null }, { name: EXE, digest: `sha256:${HASH_A}` }],
      manifest: line(HASH_A, EXE) + '\n' + '#'.repeat(MAX_MANIFEST_BYTES + 10),
    })
    const code = main({ ...silent, argv: ['v1.0.0'], env: {}, runGh, errLog: (m) => errors.push(m) })
    expect(code).toBe(EXIT_BROKEN_RELEASE)
    expect(errors.join('\n')).toMatch(/over the/)
  })

  it('prints every warning it computed', () => {
    // The platform-coverage warning is the only signal that a Linux-less
    // release shipped. Computing it and not printing it is the same as not
    // having it.
    const logs: string[] = []
    const { runGh } = fakeGh({
      assets: [
        { name: 'CHECKSUMS.txt', digest: null },
        { name: EXE, digest: `sha256:${HASH_A}` },
        { name: DMG, digest: `sha256:${HASH_B}` },
      ],
      manifest: [line(HASH_A, EXE), line(HASH_B, DMG)].join('\n') + '\n',
    })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh, log: (m) => logs.push(m) })).toBe(EXIT_OK)
    expect(logs.some((l) => l.includes('no Linux installer'))).toBe(true)
  })

  it('removes its temp directory on both the success and the failure path', () => {
    // A fixed or leaked dir would also let two concurrent runs clobber each
    // other's manifest, so the gate would verify the wrong release's bytes.
    const fsMod = require('node:fs') as typeof import('fs')
    const pathMod = require('node:path') as typeof import('path')
    const osMod = require('node:os') as typeof import('os')
    const staging = fsMod.mkdtempSync(pathMod.join(osMod.tmpdir(), 'ccc-mtest-'))
    const seen: string[] = []

    const ok = fakeGh({
      assets: [{ name: 'CHECKSUMS.txt', digest: null }, { name: EXE, digest: `sha256:${HASH_A}` }],
      manifest: line(HASH_A, EXE) + '\n',
      dirFor: (d) => seen.push(d),
    })
    main({ ...silent, argv: ['v1.0.0'], env: {}, tmpdir: () => staging, runGh: ok.runGh })

    const bad = fakeGh({ assets: [{ name: EXE, digest: `sha256:${HASH_A}` }], manifest: null })
    main({ ...silent, argv: ['v1.0.0'], env: {}, tmpdir: () => staging, runGh: bad.runGh })

    expect(seen.length).toBeGreaterThan(0)
    for (const d of seen) expect(fsMod.existsSync(d)).toBe(false)
    expect(fsMod.readdirSync(staging)).toEqual([])
  })

  it('reads the tag from $TAG when argv is empty', () => {
    const calls: string[][] = []
    const code = main({
      ...silent,
      argv: [],
      env: { TAG: 'v9.9.9' },
      runGh: (args) => {
        calls.push(args)
        throw new Error('boom')
      },
    })
    expect(code).toBe(EXIT_CANNOT_VERIFY)
    expect(calls[0]).toContain('v9.9.9')
  })

  it('exits CANNOT_VERIFY, not BROKEN_RELEASE, when the API is unavailable', () => {
    // A GitHub outage must not read as "this release is broken" — that is the
    // failure mode that teaches people to ignore the gate.
    const code = main({
      ...silent,
      argv: ['v1.0.0'],
      env: {},
      runGh: () => {
        throw new Error('HTTP 503')
      },
    })
    expect(code).toBe(EXIT_CANNOT_VERIFY)
  })

  it('exits CANNOT_VERIFY when gh returns something that is not an asset array', () => {
    const code = main({ ...silent, argv: ['v1.0.0'], env: {}, runGh: () => '{"not":"an array"}' })
    expect(code).toBe(EXIT_CANNOT_VERIFY)
  })

  it('exits BROKEN_RELEASE when the release has no CHECKSUMS.txt', () => {
    const { runGh } = fakeGh({ assets: [{ name: EXE, digest: `sha256:${HASH_A}` }], manifest: null })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh })).toBe(EXIT_BROKEN_RELEASE)
  })

  it('exits CANNOT_VERIFY when CHECKSUMS.txt is attached but cannot be fetched', () => {
    // Ambiguous state: the manifest exists, so the release may be fine and the
    // API may not be. Do not brand it broken.
    const { runGh } = fakeGh({
      assets: [{ name: 'CHECKSUMS.txt', digest: null }, { name: EXE, digest: `sha256:${HASH_A}` }],
      manifest: null,
    })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh })).toBe(EXIT_CANNOT_VERIFY)
  })

  it('exits OK on a healthy release, having actually downloaded the manifest', () => {
    const manifest = [line(HASH_A, EXE), line(HASH_B, DMG), line('c'.repeat(64), APPIMAGE)].join('\n') + '\n'
    const { runGh } = fakeGh({
      assets: [
        { name: 'CHECKSUMS.txt', digest: null },
        { name: EXE, digest: `sha256:${HASH_A}` },
        { name: DMG, digest: `sha256:${HASH_B}` },
        { name: APPIMAGE, digest: `sha256:${'c'.repeat(64)}` },
      ],
      manifest,
    })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh })).toBe(EXIT_OK)
  })

  it('exits BROKEN_RELEASE when the downloaded manifest omits an attached installer', () => {
    const { runGh } = fakeGh({
      assets: [
        { name: 'CHECKSUMS.txt', digest: null },
        { name: EXE, digest: `sha256:${HASH_A}` },
        { name: APPIMAGE, digest: `sha256:${'c'.repeat(64)}` },
      ],
      manifest: line(HASH_A, EXE) + '\n',
    })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh })).toBe(EXIT_BROKEN_RELEASE)
  })

  it('says the release is a DRAFT rather than claiming users are affected', () => {
    // On the fresh path a failed gate means nothing shipped. Telling the
    // operator the release "IS PUBLISHED" sends them to repair an incident that
    // is not happening.
    const errors: string[] = []
    const { runGh } = fakeGh({
      assets: [{ name: 'CHECKSUMS.txt', digest: null }, { name: EXE, digest: `sha256:${HASH_A}` }],
      isDraft: true,
      manifest: line(HASH_A, 'something-else.exe') + '\n',
    })
    expect(main({ ...silent, argv: ['v1.0.0'], env: {}, runGh, errLog: (m) => errors.push(m) })).toBe(EXIT_BROKEN_RELEASE)
    const text = errors.join('\n')
    expect(text).toMatch(/still a DRAFT/)
    expect(text).not.toMatch(/IS PUBLISHED/)
  })
})
