// #170 — per-account user-scope CLAUDE.md.
//
// A CCC session runs with USERPROFILE=<profileDir>, so Claude Code looks for
// user-scope instructions at <profileDir>/.claude/CLAUDE.md. Nothing created it,
// so sessions ran with NO user-scope instructions. buildHomeLinks now generates
// it from the shared ~/.claude/CLAUDE.md plus an optional per-profile overlay.
//
// The load-bearing hazard: the on-disk entry may be a HARDLINK to the real
// ~/.claude/CLAUDE.md (created outside CCC). Writing through it would corrupt the
// real file for every account, so the generator must unlink before writing.
import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'
import { _setRootsForTest, createProfile, getProfileConfigDir, setupProfileLinks } from '../../src/main/account-profiles'

let base: string
let sharedRoot: string
beforeEach(() => {
  base = fs.mkdtempSync(path.join(os.tmpdir(), 'ccc-claudemd-'))
  const resourcesDir = path.join(base, 'res')
  sharedRoot = path.join(base, 'home', '.claude')
  fs.mkdirSync(resourcesDir, { recursive: true })
  fs.mkdirSync(sharedRoot, { recursive: true })
  _setRootsForTest({ resourcesDir, sharedRoot })
})
afterEach(() => {
  _setRootsForTest(null)
  try { fs.rmSync(base, { recursive: true, force: true }) } catch { /* ignore */ }
})

const destFor = (id: string) => path.join(getProfileConfigDir(id), '.claude', 'CLAUDE.md')

describe('per-account CLAUDE.md generation (#170)', () => {
  it('generates the profile CLAUDE.md from the shared source', () => {
    fs.writeFileSync(path.join(sharedRoot, 'CLAUDE.md'), '# shared rules\nBe precise.')
    const p = createProfile('Work')
    setupProfileLinks(p.id)
    const text = fs.readFileSync(destFor(p.id), 'utf8')
    expect(text).toContain('# shared rules')
    expect(text).toContain('Be precise.')
    expect(text).toMatch(/Generated by AI Code Conductor/)
  })

  it('concatenates a per-profile overlay after the shared content', () => {
    fs.writeFileSync(path.join(sharedRoot, 'CLAUDE.md'), 'SHARED-BODY')
    const p = createProfile('Work')
    // Overlay lives in the profile's own .claude dir; create the dir first.
    const claudeDir = path.join(getProfileConfigDir(p.id), '.claude')
    fs.mkdirSync(claudeDir, { recursive: true })
    fs.writeFileSync(path.join(claudeDir, 'CLAUDE.overlay.md'), 'OVERLAY-BODY')
    setupProfileLinks(p.id)
    const text = fs.readFileSync(destFor(p.id), 'utf8')
    expect(text.indexOf('SHARED-BODY')).toBeGreaterThanOrEqual(0)
    expect(text.indexOf('OVERLAY-BODY')).toBeGreaterThan(text.indexOf('SHARED-BODY'))
    expect(text).toMatch(/Account overlay/)
  })

  it('writes nothing when neither the shared file nor an overlay exists', () => {
    const p = createProfile('Work')   // no shared CLAUDE.md, no overlay
    setupProfileLinks(p.id)
    expect(fs.existsSync(destFor(p.id))).toBe(false)
  })

  it('does not rewrite (no mtime churn) when the content is unchanged', () => {
    fs.writeFileSync(path.join(sharedRoot, 'CLAUDE.md'), 'STABLE')
    const p = createProfile('Work')
    setupProfileLinks(p.id)
    const first = fs.statSync(destFor(p.id)).mtimeMs
    // A second spawn with the same source must not touch the file.
    setupProfileLinks(p.id)
    expect(fs.statSync(destFor(p.id)).mtimeMs).toBe(first)
  })

  it('breaks a pre-existing HARDLINK instead of writing through to the real file', () => {
    // The real ~/.claude/CLAUDE.md, and a profile CLAUDE.md hardlinked to it —
    // exactly the state observed on the reporter's machine.
    // Create the profile BEFORE any shared CLAUDE.md exists, so nothing is
    // generated yet and we can plant the pre-existing hardlink ourselves.
    const p = createProfile('Work')
    const claudeDir = path.join(getProfileConfigDir(p.id), '.claude')
    fs.mkdirSync(claudeDir, { recursive: true })
    const dest = path.join(claudeDir, 'CLAUDE.md')
    try { fs.rmSync(dest, { force: true }) } catch { /* absent */ }

    const realFile = path.join(base, 'home', 'CLAUDE.md')
    fs.writeFileSync(realFile, 'REAL-ORIGINAL')
    fs.linkSync(realFile, dest)   // dest and realFile now share one inode
    // Now a shared source appears with DIFFERENT content — a rewrite must fire.
    fs.writeFileSync(path.join(sharedRoot, 'CLAUDE.md'), 'NEW-SHARED-RULES')

    setupProfileLinks(p.id)

    // The real file must be byte-for-byte untouched...
    expect(fs.readFileSync(realFile, 'utf8')).toBe('REAL-ORIGINAL')
    // ...and the profile copy must now hold the generated content. Divergent
    // content proves the hardlink was broken: a live link forces identical bytes.
    const destText = fs.readFileSync(dest, 'utf8')
    expect(destText).toContain('NEW-SHARED-RULES')
    expect(destText).not.toBe('REAL-ORIGINAL')
  })

  it('does not consume its own output when the shared root resolves to the profile (self-reference)', () => {
    // A CCC session sets USERPROFILE=<profileDir>, so sharedRoot() can resolve to
    // the profile's own .claude — making source and dest one file. Without the
    // guard each spawn wrapped a new header around the whole prior content.
    const p = createProfile('Work')
    const claudeDir = path.join(getProfileConfigDir(p.id), '.claude')
    fs.mkdirSync(claudeDir, { recursive: true })
    const dest = path.join(claudeDir, 'CLAUDE.md')
    fs.writeFileSync(dest, '# my rules')
    _setRootsForTest({ resourcesDir: path.join(base, 'res'), sharedRoot: claudeDir })
    for (let i = 0; i < 3; i++) setupProfileLinks(p.id)
    expect(fs.readFileSync(dest, 'utf8')).toBe('# my rules')
  })

  it('removes its OWN generated file when both sources vanish, but leaves a hand-authored one', () => {
    fs.writeFileSync(path.join(sharedRoot, 'CLAUDE.md'), 'RULES')
    const p = createProfile('Work')
    setupProfileLinks(p.id)
    const dest = destFor(p.id)
    expect(fs.existsSync(dest)).toBe(true)
    fs.rmSync(path.join(sharedRoot, 'CLAUDE.md'))
    setupProfileLinks(p.id)
    expect(fs.existsSync(dest)).toBe(false)              // generated file cleaned up
    fs.writeFileSync(dest, 'HAND-AUTHORED')              // user writes their own
    setupProfileLinks(p.id)
    expect(fs.readFileSync(dest, 'utf8')).toBe('HAND-AUTHORED')  // never touched
  })
})
